version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:5000
    env_file: ./backend/.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: [--auth]

volumes:
  mongodb:
